#!/bin/bash
#
# Config Ubuntu

readonly SOFTWARE_PATH="${HOME}/softwares"
readonly HIBERNATE_FILE="/etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla"

# echo on
set -x

# stop on error
set -e

# sublime text 3
./utils/install_sublime_text

# spotify
./utils/install_spotify

# flash player
./utils/install_flash_player

# obs
./utils/install_obs

# vs code
./utils/install_vs_code

pushd "${HOME}"

# install packages
sudo apt update
sudo apt install -y \
                 bleachbit \
                 build-essential \
                 chromium-browser \
                 cmake \
                 code \
                 curl \
                 dconf-tools \
                 exfat-fuse \
                 exfat-utils \
                 fcitx \
                 fcitx-googlepinyin \
                 ffmpeg \
                 gdebi-core \
                 git \
                 nautilus-dropbox \
                 snapd \
                 snapd-xdg-open \
                 vim \
                 xclip \
                 xournal \
                 unrar \
                 vlc
sudo apt upgrade

# wechat
sudo snap install electronic-wechat

# directory
rm -rf Documents Music Pictures Videos
mkdir -p "${SOFTWARE_PATH}"

# git
git config --global user.email lsmgeb89@gmail.com

# jetbrains
pushd "${SOFTWARE_PATH}"
wget -O - "https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.4.2492.tar.gz" | tar xzf -
./jetbrains-toolbox-1.4.2492/jetbrains-toolbox &
popd

# enable hibernate
# https://help.ubuntu.com/16.04/ubuntu-help/power-hibernate.html
sudo touch "${HIBERNATE_FILE}"
sudo bash -c "cat >> ${HIBERNATE_FILE}" << EOL
[Re-enable hibernate by default in upower]
Identity=unix-user:*
Action=org.freedesktop.upower.hibernate
ResultActive=yes

[Re-enable hibernate by default in logind]
Identity=unix-user:*
Action=org.freedesktop.login1.hibernate;org.freedesktop.login1.handle-hibernate-key;org.freedesktop.login1;org.freedesktop.login1.hibernate-multiple-sessions;org.freedesktop.login1.hibernate-ignore-inhibit
ResultActive=yes
EOL

# change power button to hibernate
gsettings set org.gnome.settings-daemon.plugins.power button-power suspend

# never turn off screen automatically
gsettings set org.gnome.desktop.session idle-delay 0

# do nothing when closing lid
gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action nothing
gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action nothing

# hibernate when low power
gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action suspend

popd

# use local time to avoid conflict with windows
timedatectl set-local-rtc 1

# set brightness to 60%
xrandr --output eDP-1 --brightness 0.6
