#!/bin/bash
#
# Config Ubuntu

# echo on
set -x

# stop on error
set -e

# sublime text 3
./utils/sublime_text_install

# spotify
./utils/spotify_install

# flash player
./utils/flash_player_install

# obs
./utils/obs_install

# vs code
./utils/vs_code_install

# jetbrains toolbox
./utils/jetbrains_toolbox_install

# install packages
sudo apt update
sudo apt install -y \
                 bleachbit \
                 build-essential \
                 chromium-browser \
                 cmake \
                 code \
                 curl \
                 dconf-cli \
                 dconf-editor \
                 exfat-fuse \
                 exfat-utils \
                 fcitx \
                 fcitx-googlepinyin \
                 ffmpeg \
                 gdebi-core \
                 git \
                 meld \
                 nautilus-dropbox \
                 snapd \
                 snapd-xdg-open \
                 vim \
                 xclip \
                 xournal \
                 unrar \
                 vlc
sudo apt upgrade -y

# git
git config --global user.email lsmgeb89@gmail.com
git config --global diff.tool meld
git config --global difftool.prompt false

# never turn off screen automatically
gsettings set org.gnome.desktop.session idle-delay 0

# do nothing when closing lid
gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action nothing
gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action nothing

# use local time to avoid conflict with windows
timedatectl set-local-rtc 1

# remove all unused packages
sudo apt autoremove -y

# For ThinkPad X1 Yoga 2nd only
# List monitors first: xrandr --listmonitors
# Adjust brightness on a monitor: xrandr --output <monitor_name> --brightness <point>
