#!/bin/bash
#
# Install Flash Player
# https://askubuntu.com/questions/14629/how-do-i-enable-the-partner-repository
# https://help.ubuntu.com/stable/ubuntu-help/net-install-flash.html.en

# Enable partner repository for flash player
sudo sed -i "/^# deb.* .*partner/ s/^# //" /etc/apt/sources.list

# Install flash player
sudo apt update
sudo apt install -y adobe-flashplugin browser-plugin-freshplayer-pepperflash
