#!/bin/bash
#
# Install Java Stack
# https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04

# Install the Oracle JDK
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt update
sudo apt install -y oracle-java8-installer oracle-java8-set-default maven
