#!/bin/bash
#
# Install Jetbrains Toolbox

readonly TOOLBOX_BIN="/usr/local/bin/jetbrains-toolbox"

if [ -f "$TOOLBOX_BIN" ]; then
  echo "Jetbrains Toolbox is already installed."
  exit 0
fi

cd $(dirname $0)

readonly INSTALL_SCRIPT="https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh"

sudo apt install -y curl
curl "${INSTALL_SCRIPT}" > jetbrains-toolbox.sh

chmod +x jetbrains-toolbox.sh
./jetbrains-toolbox.sh

rm jetbrains-toolbox.sh
