#!/bin/bash
#
# Install Spotify
# https://www.spotify.com/us/download/linux/

readonly PACKAGE_NAME="spotify-client"

if dpkg -l "${PACKAGE_NAME}"; then
  echo "The package ${PACKAGE_NAME} is already installed."
  exit 0
fi

# 1. Add the Spotify repository signing keys to be able to verify downloaded packages
wget -qO - https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add -

# 2. Add the Spotify repository
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

# 3. Update list of available packages
sudo apt-get update

# 4. Install Spotify
sudo apt-get install -y "${PACKAGE_NAME}"
