#!/bin/bash
#
# Install Sublime Text 3
# https://www.sublimetext.com/docs/3/linux_repositories.html#apt

readonly PACKAGE_NAME="sublime-text"

if dpkg -l "${PACKAGE_NAME}"; then
  echo "The package ${PACKAGE_NAME} is already installed."
  exit 0
fi

cd $(dirname $0)

# Install the GPG key
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

# Ensure apt is set up to work with https sources
sudo apt-get install apt-transport-https

# Select stable channel
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Update apt sources and install Sublime Text
sudo apt-get update
sudo apt-get install -y "${PACKAGE_NAME}"

# Copy config file
mkdir -p "${HOME}"/.config/sublime-text-3/Packages/User/ && cp -R ../config/sublime/Preferences.sublime-settings $_
