#!/bin/bash
#
# Install VS Code
# https://code.visualstudio.com/docs/setup/linux

cd $(dirname $0)

# Install vs code
wget -qO - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

sudo apt update
sudo apt install -y code

# config vs code
code --install-extension ms-vscode.cpptools
code --install-extension zhuangtongfa.material-theme
# code --install-extension mitaki28.vscode-clang
# code --install-extension formulahendry.code-runner
# code --install-extension ajshort.include-autocomplete
# code --install-extension hars.CppSnippets
mkdir -p "${HOME}"/.config/Code/User/ && cp -R ../config/vs_code/settings.json $_
